# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#

# estados civis
CivilEstado.destroy_all
CivilEstado.create([
  { estado: 'solteiro' },
  { estado: 'casado' },
  { estado: 'viúvo' },
  { estado: 'divorciado' }
])

# graus de instrução
InstrucaoGrau.destroy_all
InstrucaoGrau.create([
  { grau: 'analfabeto' },
  { grau: 'fundamental incompleto' },
  { grau: 'fundamental completo' },
  { grau: 'ensino médio incompleto' },
  { grau: 'ensino médio completo' },
  { grau: 'superior incompleto' },
  { grau: 'superior completo' },
  { grau: 'pós-graduação' }
])

# unidades federativas (apenas para referência, uso futuro)
Uf.destroy_all
Uf.create([
  { nome: 'Acre', sigla: 'AC' },
  { nome: 'Alagoas', sigla: 'AL' },
  { nome: 'Amapá', sigla: 'AP' },
  { nome: 'Amazonas', sigla: 'AM' },
  { nome: 'Bahia', sigla: 'BA' },
  { nome: 'Ceará', sigla: 'CE' },
  { nome: 'Distrito Federal', sigla: 'DF' },
  { nome: 'Espírito Santo', sigla: 'ES' },
  { nome: 'Goiás', sigla: 'GO' },
  { nome: 'Maranhão', sigla: 'MA' },
  { nome: 'Mato Grosso', sigla: 'MT' },
  { nome: 'Mato Grosso do Sul', sigla: 'MS' },
  { nome: 'Minas Gerais', sigla: 'MG' },
  { nome: 'Pará', sigla: 'PA' },
  { nome: 'Paraíba', sigla: 'PB' },
  { nome: 'Paraná', sigla: 'PR' },
  { nome: 'Pernambuco', sigla: 'PE' },
  { nome: 'Piauí', sigla: 'PI' },
  { nome: 'Rio de Janeiro', sigla: 'RJ' },
  { nome: 'Rio Grande do Norte', sigla: 'RN' },
  { nome: 'Rio Grande do Sul', sigla: 'RS' },
  { nome: 'Rondônia', sigla: 'RO' },
  { nome: 'Roraima', sigla: 'RR' },
  { nome: 'Santa Catarina', sigla: 'SC' },
  { nome: 'São Paulo', sigla: 'SP' },
  { nome: 'Sergipe', sigla: 'SE' },
  { nome: 'Tocantins', sigla: 'TO' }
])

# continentes
Continente.destroy_all
Continente.create([
  {:id=>2, :nome=>"América do Norte"},
  {:id=>1, :nome=>"África"},
  {:id=>3, :nome=>"América Central"},
  {:id=>4, :nome=>"América do Sul"},
  {:id=>5, :nome=>"Antártica"},
  {:id=>6, :nome=>"Ásia"},
  {:id=>7, :nome=>"Europa"},
  {:id=>8, :nome=>"Oceania"}
])

# países
Pais.destroy_all
Pais.create([
  {:id=>1,
  :nome_ingles=>"Afghanistan",
  :nome=>"Afeganistão",
  :nome_oficial=>"Emirado Islâmico do Afeganistão",
  :sigla_2=>"AF",
  :sigla_3=>"AFG",
  :iso_3166_numerico=>4,
  :continente_id=>6},
   {:id=>2,
    :nome_ingles=>"Albania",
    :nome=>"Albânia",
    :nome_oficial=>"",
    :sigla_2=>"AL",
    :sigla_3=>"ALB",
    :iso_3166_numerico=>8,
    :continente_id=>nil},
   {:id=>3,
    :nome_ingles=>"Algeria",
    :nome=>"Argélia",
    :nome_oficial=>"",
    :sigla_2=>"DZ",
    :sigla_3=>"DZA",
    :iso_3166_numerico=>12,
    :continente_id=>1},
   {:id=>4,
    :nome_ingles=>"American Samoa",
    :nome=>"Samoa Americana",
    :nome_oficial=>"",
    :sigla_2=>"AS",
    :sigla_3=>"ASM",
    :iso_3166_numerico=>16,
    :continente_id=>nil},
   {:id=>5,
    :nome_ingles=>"Andorra",
    :nome=>"Andorra",
    :nome_oficial=>"",
    :sigla_2=>"AD",
    :sigla_3=>"AND",
    :iso_3166_numerico=>20,
    :continente_id=>nil},
   {:id=>6,
    :nome_ingles=>"Angola",
    :nome=>"Angola",
    :nome_oficial=>"",
    :sigla_2=>"AO",
    :sigla_3=>"AGO",
    :iso_3166_numerico=>24,
    :continente_id=>1},
   {:id=>7,
    :nome_ingles=>"Anguilla",
    :nome=>"Anguila",
    :nome_oficial=>"",
    :sigla_2=>"AI",
    :sigla_3=>"AIA",
    :iso_3166_numerico=>660,
    :continente_id=>nil},
   {:id=>8,
    :nome_ingles=>"Antarctica",
    :nome=>"Antártica",
    :nome_oficial=>"",
    :sigla_2=>"AQ",
    :sigla_3=>"ATA",
    :iso_3166_numerico=>10,
    :continente_id=>5},
   {:id=>9,
    :nome_ingles=>"Antigua and Barbuda",
    :nome=>"Antígua e Barbuda",
    :nome_oficial=>"",
    :sigla_2=>"AG",
    :sigla_3=>"ATG",
    :iso_3166_numerico=>28,
    :continente_id=>nil},
   {:id=>10,
    :nome_ingles=>"Argentina",
    :nome=>"Argentina",
    :nome_oficial=>"",
    :sigla_2=>"AR",
    :sigla_3=>"ARG",
    :iso_3166_numerico=>32,
    :continente_id=>4},
   {:id=>11,
    :nome_ingles=>"Armenia",
    :nome=>"Armênia",
    :nome_oficial=>"",
    :sigla_2=>"AM",
    :sigla_3=>"ARM",
    :iso_3166_numerico=>51,
    :continente_id=>nil},
   {:id=>12,
    :nome_ingles=>"Aruba",
    :nome=>"Aruba",
    :nome_oficial=>"",
    :sigla_2=>"AW",
    :sigla_3=>"ABW",
    :iso_3166_numerico=>533,
    :continente_id=>nil},
   {:id=>13,
    :nome_ingles=>"Australia",
    :nome=>"Austrália",
    :nome_oficial=>"",
    :sigla_2=>"AU",
    :sigla_3=>"AUS",
    :iso_3166_numerico=>36,
    :continente_id=>8},
   {:id=>14,
    :nome_ingles=>"Austria",
    :nome=>"Áustria",
    :nome_oficial=>"",
    :sigla_2=>"AT",
    :sigla_3=>"AUT",
    :iso_3166_numerico=>40,
    :continente_id=>nil},
   {:id=>15,
    :nome_ingles=>"Azerbaijan",
    :nome=>"Azerbaidjão",
    :nome_oficial=>"",
    :sigla_2=>"AZ",
    :sigla_3=>"AZE",
    :iso_3166_numerico=>31,
    :continente_id=>nil},
   {:id=>16,
    :nome_ingles=>"Bahamas (the)",
    :nome=>"Bahamas",
    :nome_oficial=>"",
    :sigla_2=>"BS",
    :sigla_3=>"BHS",
    :iso_3166_numerico=>44,
    :continente_id=>nil},
   {:id=>17,
    :nome_ingles=>"Bahrain",
    :nome=>"Barém",
    :nome_oficial=>"",
    :sigla_2=>"BH",
    :sigla_3=>"BHR",
    :iso_3166_numerico=>48,
    :continente_id=>nil},
   {:id=>18,
    :nome_ingles=>"Bangladesh",
    :nome=>"Bangladesh",
    :nome_oficial=>"",
    :sigla_2=>"BD",
    :sigla_3=>"BGD",
    :iso_3166_numerico=>50,
    :continente_id=>nil},
   {:id=>19,
    :nome_ingles=>"Barbados",
    :nome=>"Barbados",
    :nome_oficial=>"",
    :sigla_2=>"BB",
    :sigla_3=>"BRB",
    :iso_3166_numerico=>52,
    :continente_id=>nil},
   {:id=>20,
    :nome_ingles=>"Belarus",
    :nome=>"Belarus",
    :nome_oficial=>"",
    :sigla_2=>"BY",
    :sigla_3=>"BLR",
    :iso_3166_numerico=>112,
    :continente_id=>nil},
   {:id=>21,
    :nome_ingles=>"Belgium",
    :nome=>"Bélgica",
    :nome_oficial=>"",
    :sigla_2=>"BE",
    :sigla_3=>"BEL",
    :iso_3166_numerico=>56,
    :continente_id=>7},
   {:id=>22,
    :nome_ingles=>"Belize",
    :nome=>"Belize",
    :nome_oficial=>"",
    :sigla_2=>"BZ",
    :sigla_3=>"BLZ",
    :iso_3166_numerico=>84,
    :continente_id=>nil},
   {:id=>23,
    :nome_ingles=>"Benin",
    :nome=>"Benin",
    :nome_oficial=>"",
    :sigla_2=>"BJ",
    :sigla_3=>"BEN",
    :iso_3166_numerico=>204,
    :continente_id=>nil},
   {:id=>24,
    :nome_ingles=>"Bermuda",
    :nome=>"Bermuda",
    :nome_oficial=>"",
    :sigla_2=>"BM",
    :sigla_3=>"BMU",
    :iso_3166_numerico=>60,
    :continente_id=>nil},
   {:id=>25,
    :nome_ingles=>"Bhutan",
    :nome=>"Butão",
    :nome_oficial=>"",
    :sigla_2=>"BT",
    :sigla_3=>"BTN",
    :iso_3166_numerico=>64,
    :continente_id=>nil},
   {:id=>26,
    :nome_ingles=>"Bolivia (Plurinational State of)",
    :nome=>"Bolívia",
    :nome_oficial=>"",
    :sigla_2=>"BO",
    :sigla_3=>"BOL",
    :iso_3166_numerico=>68,
    :continente_id=>4},
   {:id=>27,
    :nome_ingles=>"Bonaire, Sint Eustatius and Saba",
    :nome=>"Bonaire",
    :nome_oficial=>"",
    :sigla_2=>"BQ",
    :sigla_3=>"BES",
    :iso_3166_numerico=>535,
    :continente_id=>nil},
   {:id=>28,
    :nome_ingles=>"Bosnia and Herzegovina",
    :nome=>"Bósnia e Herzegóvina",
    :nome_oficial=>"",
    :sigla_2=>"BA",
    :sigla_3=>"BIH",
    :iso_3166_numerico=>70,
    :continente_id=>nil},
   {:id=>29,
    :nome_ingles=>"Botswana",
    :nome=>"Botsuana",
    :nome_oficial=>"",
    :sigla_2=>"BW",
    :sigla_3=>"BWA",
    :iso_3166_numerico=>72,
    :continente_id=>nil},
   {:id=>30,
    :nome_ingles=>"Bouvet Island",
    :nome=>"Ilha Bouvet",
    :nome_oficial=>"",
    :sigla_2=>"BV",
    :sigla_3=>"BVT",
    :iso_3166_numerico=>74,
    :continente_id=>nil},
   {:id=>31,
    :nome_ingles=>"Brazil",
    :nome=>"Brasil",
    :nome_oficial=>"República Federativa do Brasil",
    :sigla_2=>"BR",
    :sigla_3=>"BRA",
    :iso_3166_numerico=>76,
    :continente_id=>4},
   {:id=>32,
    :nome_ingles=>"British Indian Ocean Territory (the)",
    :nome=>"Território Britânico no Oceano Indiano",
    :nome_oficial=>"Território Britânico no Oceano Indiano",
    :sigla_2=>"IO",
    :sigla_3=>"IOT",
    :iso_3166_numerico=>86,
    :continente_id=>nil},
   {:id=>33,
    :nome_ingles=>"Brunei Darussalam",
    :nome=>"Brunei Darussalam",
    :nome_oficial=>"",
    :sigla_2=>"BN",
    :sigla_3=>"BRN",
    :iso_3166_numerico=>96,
    :continente_id=>nil},
   {:id=>34,
    :nome_ingles=>"Bulgaria",
    :nome=>"Bulgária",
    :nome_oficial=>"",
    :sigla_2=>"BG",
    :sigla_3=>"BGR",
    :iso_3166_numerico=>100,
    :continente_id=>nil},
   {:id=>35,
    :nome_ingles=>"Burkina Faso",
    :nome=>"Burquina Faso",
    :nome_oficial=>"",
    :sigla_2=>"BF",
    :sigla_3=>"BFA",
    :iso_3166_numerico=>854,
    :continente_id=>nil},
   {:id=>36,
    :nome_ingles=>"Burundi",
    :nome=>"Burundi",
    :nome_oficial=>"",
    :sigla_2=>"BI",
    :sigla_3=>"BDI",
    :iso_3166_numerico=>108,
    :continente_id=>nil},
   {:id=>37,
    :nome_ingles=>"Cabo Verde",
    :nome=>"Cabo Verde",
    :nome_oficial=>"",
    :sigla_2=>"CV",
    :sigla_3=>"CPV",
    :iso_3166_numerico=>132,
    :continente_id=>1},
   {:id=>38,
    :nome_ingles=>"Cambodia",
    :nome=>"Cambodja",
    :nome_oficial=>"",
    :sigla_2=>"KH",
    :sigla_3=>"KHM",
    :iso_3166_numerico=>116,
    :continente_id=>nil},
   {:id=>39,
    :nome_ingles=>"Cameroon",
    :nome=>"Camarões",
    :nome_oficial=>"",
    :sigla_2=>"CM",
    :sigla_3=>"CMR",
    :iso_3166_numerico=>120,
    :continente_id=>1},
   {:id=>40,
    :nome_ingles=>"Canada",
    :nome=>"Canadá",
    :nome_oficial=>"",
    :sigla_2=>"CA",
    :sigla_3=>"CAN",
    :iso_3166_numerico=>124,
    :continente_id=>2},
   {:id=>41,
    :nome_ingles=>"Cayman Islands (the)",
    :nome=>"Ilhas Cayman",
    :nome_oficial=>"",
    :sigla_2=>"KY",
    :sigla_3=>"CYM",
    :iso_3166_numerico=>136,
    :continente_id=>nil},
   {:id=>42,
    :nome_ingles=>"Central African Republic (the)",
    :nome=>"República Centro-Africana",
    :nome_oficial=>"",
    :sigla_2=>"CF",
    :sigla_3=>"CAF",
    :iso_3166_numerico=>140,
    :continente_id=>1},
   {:id=>43,
    :nome_ingles=>"Chad",
    :nome=>"Chade",
    :nome_oficial=>"",
    :sigla_2=>"TD",
    :sigla_3=>"TCD",
    :iso_3166_numerico=>148,
    :continente_id=>nil},
   {:id=>44,
    :nome_ingles=>"Chile",
    :nome=>"Chile",
    :nome_oficial=>"",
    :sigla_2=>"CL",
    :sigla_3=>"CHL",
    :iso_3166_numerico=>152,
    :continente_id=>4},
   {:id=>45,
    :nome_ingles=>"China",
    :nome=>"China",
    :nome_oficial=>"",
    :sigla_2=>"CN",
    :sigla_3=>"CHN",
    :iso_3166_numerico=>156,
    :continente_id=>6},
   {:id=>46,
    :nome_ingles=>"Christmas Island",
    :nome=>"Ilhas Natal",
    :nome_oficial=>"",
    :sigla_2=>"CX",
    :sigla_3=>"CXR",
    :iso_3166_numerico=>162,
    :continente_id=>nil},
   {:id=>47,
    :nome_ingles=>"Cocos (Keeling) Islands (the)",
    :nome=>"Ilhas Cocos",
    :nome_oficial=>"",
    :sigla_2=>"CC",
    :sigla_3=>"CCK",
    :iso_3166_numerico=>166,
    :continente_id=>nil},
   {:id=>48,
    :nome_ingles=>"Colombia",
    :nome=>"Colômbia",
    :nome_oficial=>"",
    :sigla_2=>"CO",
    :sigla_3=>"COL",
    :iso_3166_numerico=>170,
    :continente_id=>4},
   {:id=>49,
    :nome_ingles=>"Comoros (the)",
    :nome=>"Comoros",
    :nome_oficial=>"",
    :sigla_2=>"KM",
    :sigla_3=>"COM",
    :iso_3166_numerico=>174,
    :continente_id=>nil},
   {:id=>50,
    :nome_ingles=>"Congo (the Democratic Republic of the)",
    :nome=>"República Democrática do Congo",
    :nome_oficial=>"República Democrática do Congo",
    :sigla_2=>"CD",
    :sigla_3=>"COD",
    :iso_3166_numerico=>180,
    :continente_id=>nil},
   {:id=>51,
    :nome_ingles=>"Congo (the)",
    :nome=>"Congo",
    :nome_oficial=>"",
    :sigla_2=>"CG",
    :sigla_3=>"COG",
    :iso_3166_numerico=>178,
    :continente_id=>nil},
   {:id=>52,
    :nome_ingles=>"Cook Islands (the)",
    :nome=>"Ilhas Cook",
    :nome_oficial=>"",
    :sigla_2=>"CK",
    :sigla_3=>"COK",
    :iso_3166_numerico=>184,
    :continente_id=>nil},
   {:id=>53,
    :nome_ingles=>"Costa Rica",
    :nome=>"Costa Rica",
    :nome_oficial=>"",
    :sigla_2=>"CR",
    :sigla_3=>"CRI",
    :iso_3166_numerico=>188,
    :continente_id=>3},
   {:id=>54,
    :nome_ingles=>"Croatia",
    :nome=>"Croácia",
    :nome_oficial=>"",
    :sigla_2=>"HR",
    :sigla_3=>"HRV",
    :iso_3166_numerico=>191,
    :continente_id=>nil},
   {:id=>55,
    :nome_ingles=>"Cuba",
    :nome=>"Cuba",
    :nome_oficial=>"",
    :sigla_2=>"CU",
    :sigla_3=>"CUB",
    :iso_3166_numerico=>192,
    :continente_id=>3},
   {:id=>56,
    :nome_ingles=>"Curaçao",
    :nome=>"Curaçao",
    :nome_oficial=>"",
    :sigla_2=>"CW",
    :sigla_3=>"CUW",
    :iso_3166_numerico=>531,
    :continente_id=>nil},
   {:id=>57,
    :nome_ingles=>"Cyprus",
    :nome=>"Ciprinos",
    :nome_oficial=>"",
    :sigla_2=>"CY",
    :sigla_3=>"CYP",
    :iso_3166_numerico=>196,
    :continente_id=>nil},
   {:id=>58,
    :nome_ingles=>"Czechia",
    :nome=>"Tcheca",
    :nome_oficial=>"República Tcheca",
    :sigla_2=>"CZ",
    :sigla_3=>"CZE",
    :iso_3166_numerico=>203,
    :continente_id=>nil},
   {:id=>59,
    :nome_ingles=>"Côte dIvoire",
    :nome=>"Costa do Marfim",
    :nome_oficial=>"República de Côte d’Ivore",
    :sigla_2=>"CI",
    :sigla_3=>"CIV",
    :iso_3166_numerico=>384,
    :continente_id=>nil},
   {:id=>60,
    :nome_ingles=>"Denmark",
    :nome=>"Dinamarca",
    :nome_oficial=>"",
    :sigla_2=>"DK",
    :sigla_3=>"DNK",
    :iso_3166_numerico=>208,
    :continente_id=>nil},
   {:id=>61,
    :nome_ingles=>"Djibouti",
    :nome=>"Djibuti",
    :nome_oficial=>"",
    :sigla_2=>"DJ",
    :sigla_3=>"DJI",
    :iso_3166_numerico=>262,
    :continente_id=>nil},
   {:id=>62,
    :nome_ingles=>"Dominica",
    :nome=>"Dominica",
    :nome_oficial=>"",
    :sigla_2=>"DM",
    :sigla_3=>"DMA",
    :iso_3166_numerico=>212,
    :continente_id=>nil},
   {:id=>63,
    :nome_ingles=>"Dominican Republic (the)",
    :nome=>"República Dominicana",
    :nome_oficial=>"República Dominicana",
    :sigla_2=>"DO",
    :sigla_3=>"DOM",
    :iso_3166_numerico=>214,
    :continente_id=>nil},
   {:id=>64,
    :nome_ingles=>"Ecuador",
    :nome=>"Equador",
    :nome_oficial=>"",
    :sigla_2=>"EC",
    :sigla_3=>"ECU",
    :iso_3166_numerico=>218,
    :continente_id=>3},
   {:id=>65,
    :nome_ingles=>"Egypt",
    :nome=>"Egito",
    :nome_oficial=>"",
    :sigla_2=>"EG",
    :sigla_3=>"EGY",
    :iso_3166_numerico=>818,
    :continente_id=>1},
   {:id=>66,
    :nome_ingles=>"El Salvador",
    :nome=>"El Salvador",
    :nome_oficial=>"",
    :sigla_2=>"SV",
    :sigla_3=>"SLV",
    :iso_3166_numerico=>222,
    :continente_id=>3},
   {:id=>67,
    :nome_ingles=>"Equatorial Guinea",
    :nome=>"Guiné Equatorial",
    :nome_oficial=>"",
    :sigla_2=>"GQ",
    :sigla_3=>"GNQ",
    :iso_3166_numerico=>226,
    :continente_id=>nil},
   {:id=>68,
    :nome_ingles=>"Eritrea",
    :nome=>"Eritreia",
    :nome_oficial=>"Estado da Eritreia",
    :sigla_2=>"ER",
    :sigla_3=>"ERI",
    :iso_3166_numerico=>232,
    :continente_id=>nil},
   {:id=>69,
    :nome_ingles=>"Estonia",
    :nome=>"Estônia",
    :nome_oficial=>"",
    :sigla_2=>"EE",
    :sigla_3=>"EST",
    :iso_3166_numerico=>233,
    :continente_id=>nil},
   {:id=>70,
    :nome_ingles=>"Eswatini",
    :nome=>"Essuatíni",
    :nome_oficial=>"",
    :sigla_2=>"SZ",
    :sigla_3=>"SWZ",
    :iso_3166_numerico=>748,
    :continente_id=>nil},
   {:id=>71,
    :nome_ingles=>"Ethiopia",
    :nome=>"Etiópia",
    :nome_oficial=>"",
    :sigla_2=>"ET",
    :sigla_3=>"ETH",
    :iso_3166_numerico=>231,
    :continente_id=>1},
   {:id=>72,
    :nome_ingles=>"Falkland Islands (the) [Malvinas]",
    :nome=>"Ilhas Malvinas (Falkland)",
    :nome_oficial=>"",
    :sigla_2=>"FK",
    :sigla_3=>"FLK",
    :iso_3166_numerico=>238,
    :continente_id=>nil},
   {:id=>73,
    :nome_ingles=>"Faroe Islands (the)",
    :nome=>"Ilhas Faroe",
    :nome_oficial=>"",
    :sigla_2=>"FO",
    :sigla_3=>"FRO",
    :iso_3166_numerico=>234,
    :continente_id=>nil},
   {:id=>74,
    :nome_ingles=>"Fiji",
    :nome=>"Fiji",
    :nome_oficial=>"",
    :sigla_2=>"FJ",
    :sigla_3=>"FJI",
    :iso_3166_numerico=>242,
    :continente_id=>8},
   {:id=>75,
    :nome_ingles=>"Finland",
    :nome=>"Finlândia",
    :nome_oficial=>"",
    :sigla_2=>"FI",
    :sigla_3=>"FIN",
    :iso_3166_numerico=>246,
    :continente_id=>nil},
   {:id=>76,
    :nome_ingles=>"France",
    :nome=>"França",
    :nome_oficial=>"",
    :sigla_2=>"FR",
    :sigla_3=>"FRA",
    :iso_3166_numerico=>250,
    :continente_id=>7},
   {:id=>77,
    :nome_ingles=>"French Guiana",
    :nome=>"Guiana Francesa",
    :nome_oficial=>"",
    :sigla_2=>"GF",
    :sigla_3=>"GUF",
    :iso_3166_numerico=>254,
    :continente_id=>nil},
   {:id=>78,
    :nome_ingles=>"French Polynesia",
    :nome=>"Polinésia Francesa",
    :nome_oficial=>"",
    :sigla_2=>"PF",
    :sigla_3=>"PYF",
    :iso_3166_numerico=>258,
    :continente_id=>nil},
   {:id=>79,
    :nome_ingles=>"French Southern Territories (the)",
    :nome=>"Terras Austrais e Antárticas Francesas",
    :nome_oficial=>"",
    :sigla_2=>"TF",
    :sigla_3=>"ATF",
    :iso_3166_numerico=>260,
    :continente_id=>nil},
   {:id=>80,
    :nome_ingles=>"Gabon",
    :nome=>"Gabão",
    :nome_oficial=>"",
    :sigla_2=>"GA",
    :sigla_3=>"GAB",
    :iso_3166_numerico=>266,
    :continente_id=>nil},
   {:id=>81,
    :nome_ingles=>"Gambia (the)",
    :nome=>"Gambia",
    :nome_oficial=>"",
    :sigla_2=>"GM",
    :sigla_3=>"GMB",
    :iso_3166_numerico=>270,
    :continente_id=>nil},
   {:id=>82,
    :nome_ingles=>"Georgia",
    :nome=>"Geórgia",
    :nome_oficial=>"",
    :sigla_2=>"GE",
    :sigla_3=>"GEO",
    :iso_3166_numerico=>268,
    :continente_id=>nil},
   {:id=>83,
    :nome_ingles=>"Germany",
    :nome=>"Alemanha",
    :nome_oficial=>"",
    :sigla_2=>"DE",
    :sigla_3=>"DEU",
    :iso_3166_numerico=>276,
    :continente_id=>1},
   {:id=>84,
    :nome_ingles=>"Ghana",
    :nome=>"Gana",
    :nome_oficial=>"",
    :sigla_2=>"GH",
    :sigla_3=>"GHA",
    :iso_3166_numerico=>288,
    :continente_id=>nil},
   {:id=>85,
    :nome_ingles=>"Gibraltar",
    :nome=>"Gibraltar",
    :nome_oficial=>"",
    :sigla_2=>"GI",
    :sigla_3=>"GIB",
    :iso_3166_numerico=>292,
    :continente_id=>nil},
   {:id=>86,
    :nome_ingles=>"Greece",
    :nome=>"Grécia",
    :nome_oficial=>"",
    :sigla_2=>"GR",
    :sigla_3=>"GRC",
    :iso_3166_numerico=>300,
    :continente_id=>7},
   {:id=>87,
    :nome_ingles=>"Greenland",
    :nome=>"Groenlândia",
    :nome_oficial=>"",
    :sigla_2=>"GL",
    :sigla_3=>"GRL",
    :iso_3166_numerico=>304,
    :continente_id=>2},
   {:id=>88,
    :nome_ingles=>"Grenada",
    :nome=>"Grenada",
    :nome_oficial=>"",
    :sigla_2=>"GD",
    :sigla_3=>"GRD",
    :iso_3166_numerico=>308,
    :continente_id=>nil},
   {:id=>89,
    :nome_ingles=>"Guadeloupe",
    :nome=>"Guadalupe",
    :nome_oficial=>"",
    :sigla_2=>"GP",
    :sigla_3=>"GLP",
    :iso_3166_numerico=>312,
    :continente_id=>nil},
   {:id=>90,
    :nome_ingles=>"Guam",
    :nome=>"Guam",
    :nome_oficial=>"",
    :sigla_2=>"GU",
    :sigla_3=>"GUM",
    :iso_3166_numerico=>316,
    :continente_id=>nil},
   {:id=>91,
    :nome_ingles=>"Guatemala",
    :nome=>"Guatemala",
    :nome_oficial=>"",
    :sigla_2=>"GT",
    :sigla_3=>"GTM",
    :iso_3166_numerico=>320,
    :continente_id=>nil},
   {:id=>92,
    :nome_ingles=>"Guernsey",
    :nome=>"Guernsey",
    :nome_oficial=>"",
    :sigla_2=>"GG",
    :sigla_3=>"GGY",
    :iso_3166_numerico=>831,
    :continente_id=>nil},
   {:id=>93,
    :nome_ingles=>"Guinea",
    :nome=>"Guiné",
    :nome_oficial=>"",
    :sigla_2=>"GN",
    :sigla_3=>"GIN",
    :iso_3166_numerico=>324,
    :continente_id=>nil},
   {:id=>94,
    :nome_ingles=>"Guinea-Bissau",
    :nome=>"Guiné-Bissau",
    :nome_oficial=>"",
    :sigla_2=>"GW",
    :sigla_3=>"GNB",
    :iso_3166_numerico=>624,
    :continente_id=>nil},
   {:id=>95,
    :nome_ingles=>"Guyana",
    :nome=>"Guiana",
    :nome_oficial=>"",
    :sigla_2=>"GY",
    :sigla_3=>"GUY",
    :iso_3166_numerico=>328,
    :continente_id=>nil},
   {:id=>96,
    :nome_ingles=>"Haiti",
    :nome=>"Haiti",
    :nome_oficial=>"",
    :sigla_2=>"HT",
    :sigla_3=>"HTI",
    :iso_3166_numerico=>332,
    :continente_id=>3},
   {:id=>97,
    :nome_ingles=>"Heard Island and McDonald Islands",
    :nome=>"Ilha Heard e Ilhas McDonald",
    :nome_oficial=>"",
    :sigla_2=>"HM",
    :sigla_3=>"HMD",
    :iso_3166_numerico=>334,
    :continente_id=>nil},
   {:id=>98,
    :nome_ingles=>"Holy See (the)",
    :nome=>"Santa Sé",
    :nome_oficial=>"",
    :sigla_2=>"VA",
    :sigla_3=>"VAT",
    :iso_3166_numerico=>336,
    :continente_id=>nil},
   {:id=>99,
    :nome_ingles=>"Honduras",
    :nome=>"Honduras",
    :nome_oficial=>"",
    :sigla_2=>"HN",
    :sigla_3=>"HND",
    :iso_3166_numerico=>340,
    :continente_id=>nil},
   {:id=>100,
    :nome_ingles=>"Hong Kong",
    :nome=>"Hong Kong",
    :nome_oficial=>"",
    :sigla_2=>"HK",
    :sigla_3=>"HKG",
    :iso_3166_numerico=>344,
    :continente_id=>6},
   {:id=>101,
    :nome_ingles=>"Hungary",
    :nome=>"Hungria",
    :nome_oficial=>"",
    :sigla_2=>"HU",
    :sigla_3=>"HUN",
    :iso_3166_numerico=>348,
    :continente_id=>nil},
   {:id=>102,
    :nome_ingles=>"Iceland",
    :nome=>"Islândia",
    :nome_oficial=>"",
    :sigla_2=>"IS",
    :sigla_3=>"ISL",
    :iso_3166_numerico=>352,
    :continente_id=>nil},
   {:id=>103,
    :nome_ingles=>"India",
    :nome=>"Índia",
    :nome_oficial=>"",
    :sigla_2=>"IN",
    :sigla_3=>"IND",
    :iso_3166_numerico=>356,
    :continente_id=>6},
   {:id=>104,
    :nome_ingles=>"Indonesia",
    :nome=>"Indonésia",
    :nome_oficial=>"",
    :sigla_2=>"ID",
    :sigla_3=>"IDN",
    :iso_3166_numerico=>360,
    :continente_id=>6},
   {:id=>105,
    :nome_ingles=>"Iran (Islamic Republic of)",
    :nome=>"Irã",
    :nome_oficial=>"República Islâmica do Irã",
    :sigla_2=>"IR",
    :sigla_3=>"IRN",
    :iso_3166_numerico=>364,
    :continente_id=>6},
   {:id=>106,
    :nome_ingles=>"Iraq",
    :nome=>"Iraque",
    :nome_oficial=>"",
    :sigla_2=>"IQ",
    :sigla_3=>"IRQ",
    :iso_3166_numerico=>368,
    :continente_id=>6},
   {:id=>107,
    :nome_ingles=>"Ireland",
    :nome=>"Irlanda",
    :nome_oficial=>"",
    :sigla_2=>"IE",
    :sigla_3=>"IRL",
    :iso_3166_numerico=>372,
    :continente_id=>nil},
   {:id=>108,
    :nome_ingles=>"Isle of Man",
    :nome=>"Ilha de Man",
    :nome_oficial=>"",
    :sigla_2=>"IM",
    :sigla_3=>"IMN",
    :iso_3166_numerico=>833,
    :continente_id=>nil},
   {:id=>109,
    :nome_ingles=>"Israel",
    :nome=>"Israel",
    :nome_oficial=>"",
    :sigla_2=>"IL",
    :sigla_3=>"ISR",
    :iso_3166_numerico=>376,
    :continente_id=>6},
   {:id=>110,
    :nome_ingles=>"Italy",
    :nome=>"Itália",
    :nome_oficial=>"",
    :sigla_2=>"IT",
    :sigla_3=>"ITA",
    :iso_3166_numerico=>380,
    :continente_id=>7},
   {:id=>111,
    :nome_ingles=>"Jamaica",
    :nome=>"Jamaica",
    :nome_oficial=>"",
    :sigla_2=>"JM",
    :sigla_3=>"JAM",
    :iso_3166_numerico=>388,
    :continente_id=>1},
   {:id=>112,
    :nome_ingles=>"Japan",
    :nome=>"Japão",
    :nome_oficial=>"",
    :sigla_2=>"JP",
    :sigla_3=>"JPN",
    :iso_3166_numerico=>392,
    :continente_id=>6},
   {:id=>113,
    :nome_ingles=>"Jersey",
    :nome=>"Jersey",
    :nome_oficial=>"",
    :sigla_2=>"JE",
    :sigla_3=>"JEY",
    :iso_3166_numerico=>832,
    :continente_id=>nil},
   {:id=>114,
    :nome_ingles=>"Jordan",
    :nome=>"Jordânia",
    :nome_oficial=>"",
    :sigla_2=>"JO",
    :sigla_3=>"JOR",
    :iso_3166_numerico=>400,
    :continente_id=>6},
   {:id=>115,
    :nome_ingles=>"Kazakhstan",
    :nome=>"Cazaquistão",
    :nome_oficial=>"",
    :sigla_2=>"KZ",
    :sigla_3=>"KAZ",
    :iso_3166_numerico=>398,
    :continente_id=>6},
   {:id=>116,
    :nome_ingles=>"Kenya",
    :nome=>"Quênia",
    :nome_oficial=>"",
    :sigla_2=>"KE",
    :sigla_3=>"KEN",
    :iso_3166_numerico=>404,
    :continente_id=>1},
   {:id=>117,
    :nome_ingles=>"Kiribati",
    :nome=>"Kiribati",
    :nome_oficial=>"",
    :sigla_2=>"KI",
    :sigla_3=>"KIR",
    :iso_3166_numerico=>296,
    :continente_id=>nil},
   {:id=>118,
    :nome_ingles=>"Korea (the Democratic Peoples Republic of)",
    :nome=>"Coreia do Norte",
    :nome_oficial=>"República Popular Democrática da Coréia",
    :sigla_2=>"KP",
    :sigla_3=>"PRK",
    :iso_3166_numerico=>408,
    :continente_id=>6},
   {:id=>119,
    :nome_ingles=>"Korea (the Republic of)",
    :nome=>"Coreia do Sul",
    :nome_oficial=>"República da Coreia",
    :sigla_2=>"KR",
    :sigla_3=>"KOR",
    :iso_3166_numerico=>410,
    :continente_id=>6},
   {:id=>120,
    :nome_ingles=>"Kuwait",
    :nome=>"Kuwait",
    :nome_oficial=>"",
    :sigla_2=>"KW",
    :sigla_3=>"KWT",
    :iso_3166_numerico=>414,
    :continente_id=>6},
   {:id=>121,
    :nome_ingles=>"Kyrgyzstan",
    :nome=>"Quirguistão",
    :nome_oficial=>"República Quirguiz",
    :sigla_2=>"KG",
    :sigla_3=>"KGZ",
    :iso_3166_numerico=>417,
    :continente_id=>nil},
   {:id=>122,
    :nome_ingles=>"Lao Peoples Democratic Republic (the)",
    :nome=>"Laos",
    :nome_oficial=>"República Popular Democrática do Laos",
    :sigla_2=>"LA",
    :sigla_3=>"LAO",
    :iso_3166_numerico=>418,
    :continente_id=>nil},
   {:id=>123,
    :nome_ingles=>"Latvia",
    :nome=>"Látia",
    :nome_oficial=>"",
    :sigla_2=>"LV",
    :sigla_3=>"LVA",
    :iso_3166_numerico=>428,
    :continente_id=>nil},
   {:id=>124,
    :nome_ingles=>"Lebanon",
    :nome=>"Líbano",
    :nome_oficial=>"",
    :sigla_2=>"LB",
    :sigla_3=>"LBN",
    :iso_3166_numerico=>422,
    :continente_id=>6},
   {:id=>125,
    :nome_ingles=>"Lesotho",
    :nome=>"Lesoto",
    :nome_oficial=>"",
    :sigla_2=>"LS",
    :sigla_3=>"LSO",
    :iso_3166_numerico=>426,
    :continente_id=>nil},
   {:id=>126,
    :nome_ingles=>"Liberia",
    :nome=>"Libéria",
    :nome_oficial=>"",
    :sigla_2=>"LR",
    :sigla_3=>"LBR",
    :iso_3166_numerico=>430,
    :continente_id=>nil},
   {:id=>127,
    :nome_ingles=>"Libya",
    :nome=>"Líbia",
    :nome_oficial=>"",
    :sigla_2=>"LY",
    :sigla_3=>"LBY",
    :iso_3166_numerico=>434,
    :continente_id=>nil},
   {:id=>128,
    :nome_ingles=>"Liechtenstein",
    :nome=>"Liechtenstein",
    :nome_oficial=>"",
    :sigla_2=>"LI",
    :sigla_3=>"LIE",
    :iso_3166_numerico=>438,
    :continente_id=>nil},
   {:id=>129,
    :nome_ingles=>"Lithuania",
    :nome=>"Lituânia",
    :nome_oficial=>"",
    :sigla_2=>"LT",
    :sigla_3=>"LTU",
    :iso_3166_numerico=>440,
    :continente_id=>nil},
   {:id=>130,
    :nome_ingles=>"Luxembourg",
    :nome=>"Luxemburgo",
    :nome_oficial=>"",
    :sigla_2=>"LU",
    :sigla_3=>"LUX",
    :iso_3166_numerico=>442,
    :continente_id=>nil},
   {:id=>131,
    :nome_ingles=>"Macao",
    :nome=>"Macau",
    :nome_oficial=>"",
    :sigla_2=>"MO",
    :sigla_3=>"MAC",
    :iso_3166_numerico=>446,
    :continente_id=>nil},
   {:id=>132,
    :nome_ingles=>"Madagascar",
    :nome=>"Madagascar",
    :nome_oficial=>"",
    :sigla_2=>"MG",
    :sigla_3=>"MDG",
    :iso_3166_numerico=>450,
    :continente_id=>1},
   {:id=>133,
    :nome_ingles=>"Malawi",
    :nome=>"Malawi",
    :nome_oficial=>"",
    :sigla_2=>"MW",
    :sigla_3=>"MWI",
    :iso_3166_numerico=>454,
    :continente_id=>nil},
   {:id=>134,
    :nome_ingles=>"Malaysia",
    :nome=>"Malásia",
    :nome_oficial=>"",
    :sigla_2=>"MY",
    :sigla_3=>"MYS",
    :iso_3166_numerico=>458,
    :continente_id=>1},
   {:id=>135,
    :nome_ingles=>"Maldives",
    :nome=>"Maldivas",
    :nome_oficial=>"",
    :sigla_2=>"MV",
    :sigla_3=>"MDV",
    :iso_3166_numerico=>462,
    :continente_id=>nil},
   {:id=>136,
    :nome_ingles=>"Mali",
    :nome=>"Mali",
    :nome_oficial=>"",
    :sigla_2=>"ML",
    :sigla_3=>"MLI",
    :iso_3166_numerico=>466,
    :continente_id=>nil},
   {:id=>137,
    :nome_ingles=>"Malta",
    :nome=>"Malta",
    :nome_oficial=>"",
    :sigla_2=>"MT",
    :sigla_3=>"MLT",
    :iso_3166_numerico=>470,
    :continente_id=>nil},
   {:id=>138,
    :nome_ingles=>"Marshall Islands (the)",
    :nome=>"Ilhas Marshall",
    :nome_oficial=>"",
    :sigla_2=>"MH",
    :sigla_3=>"MHL",
    :iso_3166_numerico=>584,
    :continente_id=>nil},
   {:id=>139,
    :nome_ingles=>"Martinique",
    :nome=>"Martinica",
    :nome_oficial=>"",
    :sigla_2=>"MQ",
    :sigla_3=>"MTQ",
    :iso_3166_numerico=>474,
    :continente_id=>nil},
   {:id=>140,
    :nome_ingles=>"Mauritania",
    :nome=>"Mauritânia",
    :nome_oficial=>"",
    :sigla_2=>"MR",
    :sigla_3=>"MRT",
    :iso_3166_numerico=>478,
    :continente_id=>nil},
   {:id=>141,
    :nome_ingles=>"Mauritius",
    :nome=>"Maurício",
    :nome_oficial=>"República de Maurício",
    :sigla_2=>"MU",
    :sigla_3=>"MUS",
    :iso_3166_numerico=>480,
    :continente_id=>nil},
   {:id=>142,
    :nome_ingles=>"Mayotte",
    :nome=>"Mayotte",
    :nome_oficial=>"",
    :sigla_2=>"YT",
    :sigla_3=>"MYT",
    :iso_3166_numerico=>175,
    :continente_id=>nil},
   {:id=>143,
    :nome_ingles=>"Mexico",
    :nome=>"México",
    :nome_oficial=>"",
    :sigla_2=>"MX",
    :sigla_3=>"MEX",
    :iso_3166_numerico=>484,
    :continente_id=>3},
   {:id=>144,
    :nome_ingles=>"Micronesia (Federated States of)",
    :nome=>"Micronésia",
    :nome_oficial=>"",
    :sigla_2=>"FM",
    :sigla_3=>"FSM",
    :iso_3166_numerico=>583,
    :continente_id=>nil},
   {:id=>145,
    :nome_ingles=>"Moldova (the Republic of)",
    :nome=>"Moldova",
    :nome_oficial=>"República da Moldova",
    :sigla_2=>"MD",
    :sigla_3=>"MDA",
    :iso_3166_numerico=>498,
    :continente_id=>nil},
   {:id=>146,
    :nome_ingles=>"Monaco",
    :nome=>"Mônaco",
    :nome_oficial=>"",
    :sigla_2=>"MC",
    :sigla_3=>"MCO",
    :iso_3166_numerico=>492,
    :continente_id=>nil},
   {:id=>147,
    :nome_ingles=>"Mongolia",
    :nome=>"Mongólia",
    :nome_oficial=>"",
    :sigla_2=>"MN",
    :sigla_3=>"MNG",
    :iso_3166_numerico=>496,
    :continente_id=>nil},
   {:id=>148,
    :nome_ingles=>"Montenegro",
    :nome=>"Montenegro",
    :nome_oficial=>"",
    :sigla_2=>"ME",
    :sigla_3=>"MNE",
    :iso_3166_numerico=>499,
    :continente_id=>nil},
   {:id=>149,
    :nome_ingles=>"Montserrat",
    :nome=>"Montserrat",
    :nome_oficial=>"",
    :sigla_2=>"MS",
    :sigla_3=>"MSR",
    :iso_3166_numerico=>500,
    :continente_id=>nil},
   {:id=>150,
    :nome_ingles=>"Morocco",
    :nome=>"Marrocos",
    :nome_oficial=>"",
    :sigla_2=>"MA",
    :sigla_3=>"MAR",
    :iso_3166_numerico=>504,
    :continente_id=>nil},
   {:id=>151,
    :nome_ingles=>"Mozambique",
    :nome=>"Moçambique",
    :nome_oficial=>"",
    :sigla_2=>"MZ",
    :sigla_3=>"MOZ",
    :iso_3166_numerico=>508,
    :continente_id=>nil},
   {:id=>152,
    :nome_ingles=>"Myanmar",
    :nome=>"Myanmar",
    :nome_oficial=>"",
    :sigla_2=>"MM",
    :sigla_3=>"MMR",
    :iso_3166_numerico=>104,
    :continente_id=>nil},
   {:id=>153,
    :nome_ingles=>"Namibia",
    :nome=>"Namíbia",
    :nome_oficial=>"",
    :sigla_2=>"NA",
    :sigla_3=>"NAM",
    :iso_3166_numerico=>516,
    :continente_id=>nil},
   {:id=>154,
    :nome_ingles=>"Nauru",
    :nome=>"Nauru",
    :nome_oficial=>"",
    :sigla_2=>"NR",
    :sigla_3=>"NRU",
    :iso_3166_numerico=>520,
    :continente_id=>nil},
   {:id=>155,
    :nome_ingles=>"Nepal",
    :nome=>"Nepal",
    :nome_oficial=>"",
    :sigla_2=>"NP",
    :sigla_3=>"NPL",
    :iso_3166_numerico=>524,
    :continente_id=>nil},
   {:id=>156,
    :nome_ingles=>"Netherlands (the)",
    :nome=>"Holanda",
    :nome_oficial=>"",
    :sigla_2=>"NL",
    :sigla_3=>"NLD",
    :iso_3166_numerico=>528,
    :continente_id=>7},
   {:id=>157,
    :nome_ingles=>"New Caledonia",
    :nome=>"Nova Caledônia",
    :nome_oficial=>"",
    :sigla_2=>"NC",
    :sigla_3=>"NCL",
    :iso_3166_numerico=>540,
    :continente_id=>nil},
   {:id=>158,
    :nome_ingles=>"New Zealand",
    :nome=>"Nova Zelândia",
    :nome_oficial=>"",
    :sigla_2=>"NZ",
    :sigla_3=>"NZL",
    :iso_3166_numerico=>554,
    :continente_id=>nil},
   {:id=>159,
    :nome_ingles=>"Nicaragua",
    :nome=>"Nicarágua",
    :nome_oficial=>"",
    :sigla_2=>"NI",
    :sigla_3=>"NIC",
    :iso_3166_numerico=>558,
    :continente_id=>nil},
   {:id=>160,
    :nome_ingles=>"Niger (the)",
    :nome=>"Níger",
    :nome_oficial=>"",
    :sigla_2=>"NE",
    :sigla_3=>"NER",
    :iso_3166_numerico=>562,
    :continente_id=>1},
   {:id=>161,
    :nome_ingles=>"Nigeria",
    :nome=>"Nigéria",
    :nome_oficial=>"",
    :sigla_2=>"NG",
    :sigla_3=>"NGA",
    :iso_3166_numerico=>566,
    :continente_id=>1},
   {:id=>162,
    :nome_ingles=>"Niue",
    :nome=>"Niue",
    :nome_oficial=>"",
    :sigla_2=>"NU",
    :sigla_3=>"NIU",
    :iso_3166_numerico=>570,
    :continente_id=>nil},
   {:id=>163,
    :nome_ingles=>"Norfolk Island",
    :nome=>"Ilha Norfolk",
    :nome_oficial=>"",
    :sigla_2=>"NF",
    :sigla_3=>"NFK",
    :iso_3166_numerico=>574,
    :continente_id=>nil},
   {:id=>164,
    :nome_ingles=>"Northern Mariana Islands (the)",
    :nome=>"Ilhas Marianas do Norte",
    :nome_oficial=>"Comunidade das Ilhas Marianas Setentrionais",
    :sigla_2=>"MP",
    :sigla_3=>"MNP",
    :iso_3166_numerico=>580,
    :continente_id=>nil},
   {:id=>165,
    :nome_ingles=>"Norway",
    :nome=>"Noruega",
    :nome_oficial=>"",
    :sigla_2=>"NO",
    :sigla_3=>"NOR",
    :iso_3166_numerico=>578,
    :continente_id=>nil},
   {:id=>166,
    :nome_ingles=>"Oman",
    :nome=>"Omã",
    :nome_oficial=>"Sultanato de Omã",
    :sigla_2=>"OM",
    :sigla_3=>"OMN",
    :iso_3166_numerico=>512,
    :continente_id=>nil},
   {:id=>167,
    :nome_ingles=>"Pakistan",
    :nome=>"Paquistão",
    :nome_oficial=>"",
    :sigla_2=>"PK",
    :sigla_3=>"PAK",
    :iso_3166_numerico=>586,
    :continente_id=>6},
   {:id=>168,
    :nome_ingles=>"Palau",
    :nome=>"Palau",
    :nome_oficial=>"",
    :sigla_2=>"PW",
    :sigla_3=>"PLW",
    :iso_3166_numerico=>585,
    :continente_id=>nil},
   {:id=>169,
    :nome_ingles=>"Palestine, State of",
    :nome=>"Palestina",
    :nome_oficial=>"Estado da Palestina",
    :sigla_2=>"PS",
    :sigla_3=>"PSE",
    :iso_3166_numerico=>275,
    :continente_id=>6},
   {:id=>170,
    :nome_ingles=>"Panama",
    :nome=>"Panamá",
    :nome_oficial=>"",
    :sigla_2=>"PA",
    :sigla_3=>"PAN",
    :iso_3166_numerico=>591,
    :continente_id=>nil},
   {:id=>171,
    :nome_ingles=>"Papua New Guinea",
    :nome=>"Papua Nova Guiné",
    :nome_oficial=>"",
    :sigla_2=>"PG",
    :sigla_3=>"PNG",
    :iso_3166_numerico=>598,
    :continente_id=>nil},
   {:id=>172,
    :nome_ingles=>"Paraguay",
    :nome=>"Paraguai",
    :nome_oficial=>"",
    :sigla_2=>"PY",
    :sigla_3=>"PRY",
    :iso_3166_numerico=>600,
    :continente_id=>4},
   {:id=>173,
    :nome_ingles=>"Peru",
    :nome=>"Peru",
    :nome_oficial=>"",
    :sigla_2=>"PE",
    :sigla_3=>"PER",
    :iso_3166_numerico=>604,
    :continente_id=>4},
   {:id=>174,
    :nome_ingles=>"Philippines (the)",
    :nome=>"Filipinas",
    :nome_oficial=>"",
    :sigla_2=>"PH",
    :sigla_3=>"PHL",
    :iso_3166_numerico=>608,
    :continente_id=>nil},
   {:id=>175,
    :nome_ingles=>"Pitcairn",
    :nome=>"Pitcairn",
    :nome_oficial=>"",
    :sigla_2=>"PN",
    :sigla_3=>"PCN",
    :iso_3166_numerico=>612,
    :continente_id=>nil},
   {:id=>176,
    :nome_ingles=>"Poland",
    :nome=>"Polônia",
    :nome_oficial=>"República da Polônia",
    :sigla_2=>"PL",
    :sigla_3=>"POL",
    :iso_3166_numerico=>616,
    :continente_id=>nil},
   {:id=>177,
    :nome_ingles=>"Portugal",
    :nome=>"Portugal",
    :nome_oficial=>"",
    :sigla_2=>"PT",
    :sigla_3=>"PRT",
    :iso_3166_numerico=>620,
    :continente_id=>7},
   {:id=>178,
    :nome_ingles=>"Puerto Rico",
    :nome=>"Porto Rico",
    :nome_oficial=>"",
    :sigla_2=>"PR",
    :sigla_3=>"PRI",
    :iso_3166_numerico=>630,
    :continente_id=>3},
   {:id=>179,
    :nome_ingles=>"Qatar",
    :nome=>"Catar",
    :nome_oficial=>"",
    :sigla_2=>"QA",
    :sigla_3=>"QAT",
    :iso_3166_numerico=>634,
    :continente_id=>6},
   {:id=>180,
    :nome_ingles=>"Republic of North Macedonia",
    :nome=>"República da Macedônia do Norte",
    :nome_oficial=>"República da Macedônia do Norte",
    :sigla_2=>"MK",
    :sigla_3=>"MKD",
    :iso_3166_numerico=>807,
    :continente_id=>nil},
   {:id=>181,
    :nome_ingles=>"Romania",
    :nome=>"România",
    :nome_oficial=>"",
    :sigla_2=>"RO",
    :sigla_3=>"ROU",
    :iso_3166_numerico=>642,
    :continente_id=>nil},
   {:id=>182,
    :nome_ingles=>"Russian Federation (the)",
    :nome=>"Rússia",
    :nome_oficial=>"Federação Russa",
    :sigla_2=>"RU",
    :sigla_3=>"RUS",
    :iso_3166_numerico=>643,
    :continente_id=>7},
   {:id=>183,
    :nome_ingles=>"Rwanda",
    :nome=>"Ruanda",
    :nome_oficial=>"",
    :sigla_2=>"RW",
    :sigla_3=>"RWA",
    :iso_3166_numerico=>646,
    :continente_id=>nil},
   {:id=>184,
    :nome_ingles=>"Réunion",
    :nome=>"Reunião",
    :nome_oficial=>"",
    :sigla_2=>"RE",
    :sigla_3=>"REU",
    :iso_3166_numerico=>638,
    :continente_id=>nil},
   {:id=>185,
    :nome_ingles=>"Saint Barthélemy",
    :nome=>"São Bartolomeu",
    :nome_oficial=>"Coletividade de São Bartolomeu",
    :sigla_2=>"BL",
    :sigla_3=>"BLM",
    :iso_3166_numerico=>652,
    :continente_id=>nil},
   {:id=>186,
    :nome_ingles=>"Saint Helena, Ascension and Tristan da Cunha",
    :nome=>"Santa Helena, Ascensão e Tristão da Cunha",
    :nome_oficial=>"",
    :sigla_2=>"SH",
    :sigla_3=>"SHN",
    :iso_3166_numerico=>654,
    :continente_id=>nil},
   {:id=>187,
    :nome_ingles=>"Saint Kitts and Nevis",
    :nome=>"São Cristóvão e Nevis",
    :nome_oficial=>"Federação de São Cristóvão e Nevis",
    :sigla_2=>"KN",
    :sigla_3=>"KNA",
    :iso_3166_numerico=>659,
    :continente_id=>nil},
   {:id=>188,
    :nome_ingles=>"Saint Lucia",
    :nome=>"Santa Lúcia",
    :nome_oficial=>"",
    :sigla_2=>"LC",
    :sigla_3=>"LCA",
    :iso_3166_numerico=>662,
    :continente_id=>nil},
   {:id=>189,
    :nome_ingles=>"Saint Martin (French part)",
    :nome=>"São Martinho",
    :nome_oficial=>"Coletividade de São Martinho",
    :sigla_2=>"MF",
    :sigla_3=>"MAF",
    :iso_3166_numerico=>663,
    :continente_id=>nil},
   {:id=>190,
    :nome_ingles=>"Saint Pierre and Miquelon",
    :nome=>"São Pedro e Miquelon",
    :nome_oficial=>"Coletividade de Ultramar de São Pedro e Miquelon",
    :sigla_2=>"PM",
    :sigla_3=>"SPM",
    :iso_3166_numerico=>666,
    :continente_id=>nil},
   {:id=>191,
    :nome_ingles=>"Saint Vincent and the Grenadines",
    :nome=>"São Vicente e Granadinas",
    :nome_oficial=>"São Vicente e Granadinas",
    :sigla_2=>"VC",
    :sigla_3=>"VCT",
    :iso_3166_numerico=>670,
    :continente_id=>nil},
   {:id=>192,
    :nome_ingles=>"Samoa",
    :nome=>"Samoa",
    :nome_oficial=>"",
    :sigla_2=>"WS",
    :sigla_3=>"WSM",
    :iso_3166_numerico=>882,
    :continente_id=>nil},
   {:id=>193,
    :nome_ingles=>"San Marino",
    :nome=>"San Marino",
    :nome_oficial=>"Sereníssima República de San Marino",
    :sigla_2=>"SM",
    :sigla_3=>"SMR",
    :iso_3166_numerico=>674,
    :continente_id=>nil},
   {:id=>194,
    :nome_ingles=>"Sao Tome and Principe",
    :nome=>"São Tomé e Príncipe",
    :nome_oficial=>"",
    :sigla_2=>"ST",
    :sigla_3=>"STP",
    :iso_3166_numerico=>678,
    :continente_id=>nil},
   {:id=>195,
    :nome_ingles=>"Saudi Arabia",
    :nome=>"Arábia Saudita",
    :nome_oficial=>"",
    :sigla_2=>"SA",
    :sigla_3=>"SAU",
    :iso_3166_numerico=>682,
    :continente_id=>nil},
   {:id=>196,
    :nome_ingles=>"Senegal",
    :nome=>"Senegal",
    :nome_oficial=>"",
    :sigla_2=>"SN",
    :sigla_3=>"SEN",
    :iso_3166_numerico=>686,
    :continente_id=>nil},
   {:id=>197,
    :nome_ingles=>"Serbia",
    :nome=>"Sérvia",
    :nome_oficial=>"",
    :sigla_2=>"RS",
    :sigla_3=>"SRB",
    :iso_3166_numerico=>688,
    :continente_id=>nil},
   {:id=>198,
    :nome_ingles=>"Seychelles",
    :nome=>"Seychelles",
    :nome_oficial=>"",
    :sigla_2=>"SC",
    :sigla_3=>"SYC",
    :iso_3166_numerico=>690,
    :continente_id=>nil},
   {:id=>199,
    :nome_ingles=>"Sierra Leone",
    :nome=>"Serra Leoa",
    :nome_oficial=>"",
    :sigla_2=>"SL",
    :sigla_3=>"SLE",
    :iso_3166_numerico=>694,
    :continente_id=>nil},
   {:id=>200,
    :nome_ingles=>"Singapore",
    :nome=>"Singapura",
    :nome_oficial=>"",
    :sigla_2=>"SG",
    :sigla_3=>"SGP",
    :iso_3166_numerico=>702,
    :continente_id=>nil},
   {:id=>201,
    :nome_ingles=>"Sint Maarten (Dutch part)",
    :nome=>"São Martinho (Países Baixos)",
    :nome_oficial=>"",
    :sigla_2=>"SX",
    :sigla_3=>"SXM",
    :iso_3166_numerico=>534,
    :continente_id=>nil},
   {:id=>202,
    :nome_ingles=>"Slovakia",
    :nome=>"Eslováquia",
    :nome_oficial=>"",
    :sigla_2=>"SK",
    :sigla_3=>"SVK",
    :iso_3166_numerico=>703,
    :continente_id=>nil},
   {:id=>203,
    :nome_ingles=>"Slovenia",
    :nome=>"Eslovênia",
    :nome_oficial=>"",
    :sigla_2=>"SI",
    :sigla_3=>"SVN",
    :iso_3166_numerico=>705,
    :continente_id=>nil},
   {:id=>204,
    :nome_ingles=>"Solomon Islands",
    :nome=>"Ilhas Salomão",
    :nome_oficial=>"",
    :sigla_2=>"SB",
    :sigla_3=>"SLB",
    :iso_3166_numerico=>90,
    :continente_id=>nil},
   {:id=>205,
    :nome_ingles=>"Somalia",
    :nome=>"Somália",
    :nome_oficial=>"",
    :sigla_2=>"SO",
    :sigla_3=>"SOM",
    :iso_3166_numerico=>706,
    :continente_id=>nil},
   {:id=>206,
    :nome_ingles=>"South Africa",
    :nome=>"África do Sul",
    :nome_oficial=>"",
    :sigla_2=>"ZA",
    :sigla_3=>"ZAF",
    :iso_3166_numerico=>710,
    :continente_id=>1},
   {:id=>207,
    :nome_ingles=>"South Georgia and the South Sandwich Islands",
    :nome=>"Ilhas Geórgia do Sul e Sandwich do Sul",
    :nome_oficial=>"Ilhas Geórgia do Sul e Sandwich do Sul",
    :sigla_2=>"GS",
    :sigla_3=>"SGS",
    :iso_3166_numerico=>239,
    :continente_id=>nil},
   {:id=>208,
    :nome_ingles=>"South Sudan",
    :nome=>"Sudão do Sul",
    :nome_oficial=>"",
    :sigla_2=>"SS",
    :sigla_3=>"SSD",
    :iso_3166_numerico=>728,
    :continente_id=>nil},
   {:id=>209,
    :nome_ingles=>"Spain",
    :nome=>"Espanha",
    :nome_oficial=>"",
    :sigla_2=>"ES",
    :sigla_3=>"ESP",
    :iso_3166_numerico=>724,
    :continente_id=>7},
   {:id=>210,
    :nome_ingles=>"Sri Lanka",
    :nome=>"Sri Lanka",
    :nome_oficial=>"",
    :sigla_2=>"LK",
    :sigla_3=>"LKA",
    :iso_3166_numerico=>144,
    :continente_id=>nil},
   {:id=>211,
    :nome_ingles=>"Sudan (the)",
    :nome=>"Sudão",
    :nome_oficial=>"",
    :sigla_2=>"SD",
    :sigla_3=>"SDN",
    :iso_3166_numerico=>729,
    :continente_id=>6},
   {:id=>212,
    :nome_ingles=>"Suriname",
    :nome=>"Suriname",
    :nome_oficial=>"",
    :sigla_2=>"SR",
    :sigla_3=>"SUR",
    :iso_3166_numerico=>740,
    :continente_id=>nil},
   {:id=>213,
    :nome_ingles=>"Svalbard and Jan Mayen",
    :nome=>"Svalbard and Jan Mayen",
    :nome_oficial=>"",
    :sigla_2=>"SJ",
    :sigla_3=>"SJM",
    :iso_3166_numerico=>744,
    :continente_id=>nil},
   {:id=>214,
    :nome_ingles=>"Sweden",
    :nome=>"Suécia",
    :nome_oficial=>"",
    :sigla_2=>"SE",
    :sigla_3=>"SWE",
    :iso_3166_numerico=>752,
    :continente_id=>7},
   {:id=>215,
    :nome_ingles=>"Switzerland",
    :nome=>"Suíça",
    :nome_oficial=>"",
    :sigla_2=>"CH",
    :sigla_3=>"CHE",
    :iso_3166_numerico=>756,
    :continente_id=>7},
   {:id=>216,
    :nome_ingles=>"Syrian Arab Republic",
    :nome=>"República Árabe Síria",
    :nome_oficial=>"República Árabe Síria",
    :sigla_2=>"SY",
    :sigla_3=>"SYR",
    :iso_3166_numerico=>760,
    :continente_id=>nil},
   {:id=>217,
    :nome_ingles=>"Taiwan (Province of China)",
    :nome=>"Taiwan",
    :nome_oficial=>"",
    :sigla_2=>"TW",
    :sigla_3=>"TWN",
    :iso_3166_numerico=>158,
    :continente_id=>6},
   {:id=>218,
    :nome_ingles=>"Tajikistan",
    :nome=>"Tajiquistão",
    :nome_oficial=>"",
    :sigla_2=>"TJ",
    :sigla_3=>"TJK",
    :iso_3166_numerico=>762,
    :continente_id=>nil},
   {:id=>219,
    :nome_ingles=>"Tanzania, United Republic of",
    :nome=>"Tanzânia",
    :nome_oficial=>"República Unida da Tanzânia",
    :sigla_2=>"TZ",
    :sigla_3=>"TZA",
    :iso_3166_numerico=>834,
    :continente_id=>nil},
   {:id=>220,
    :nome_ingles=>"Thailand",
    :nome=>"Tailândia",
    :nome_oficial=>"",
    :sigla_2=>"TH",
    :sigla_3=>"THA",
    :iso_3166_numerico=>764,
    :continente_id=>nil},
   {:id=>221,
    :nome_ingles=>"Timor-Leste",
    :nome=>"Timor-Leste",
    :nome_oficial=>"",
    :sigla_2=>"TL",
    :sigla_3=>"TLS",
    :iso_3166_numerico=>626,
    :continente_id=>nil},
   {:id=>222,
    :nome_ingles=>"Togo",
    :nome=>"Togo",
    :nome_oficial=>"",
    :sigla_2=>"TG",
    :sigla_3=>"TGO",
    :iso_3166_numerico=>768,
    :continente_id=>nil},
   {:id=>223,
    :nome_ingles=>"Tokelau",
    :nome=>"Tokelau",
    :nome_oficial=>"",
    :sigla_2=>"TK",
    :sigla_3=>"TKL",
    :iso_3166_numerico=>772,
    :continente_id=>nil},
   {:id=>224,
    :nome_ingles=>"Tonga",
    :nome=>"Tonga",
    :nome_oficial=>"",
    :sigla_2=>"TO",
    :sigla_3=>"TON",
    :iso_3166_numerico=>776,
    :continente_id=>nil},
   {:id=>225,
    :nome_ingles=>"Trinidad and Tobago",
    :nome=>"Trinidade e Tobago",
    :nome_oficial=>"",
    :sigla_2=>"TT",
    :sigla_3=>"TTO",
    :iso_3166_numerico=>780,
    :continente_id=>nil},
   {:id=>226,
    :nome_ingles=>"Tunisia",
    :nome=>"Tunísia",
    :nome_oficial=>"",
    :sigla_2=>"TN",
    :sigla_3=>"TUN",
    :iso_3166_numerico=>788,
    :continente_id=>nil},
   {:id=>227,
    :nome_ingles=>"Turkey",
    :nome=>"Turquia",
    :nome_oficial=>"",
    :sigla_2=>"TR",
    :sigla_3=>"TUR",
    :iso_3166_numerico=>792,
    :continente_id=>6},
   {:id=>228,
    :nome_ingles=>"Turkmenistan",
    :nome=>"Turcomenistão",
    :nome_oficial=>"",
    :sigla_2=>"TM",
    :sigla_3=>"TKM",
    :iso_3166_numerico=>795,
    :continente_id=>nil},
   {:id=>229,
    :nome_ingles=>"Turks and Caicos Islands (the)",
    :nome=>"Ilhas Turcas e Caicos",
    :nome_oficial=>"Ilhas Turcas e Caicos",
    :sigla_2=>"TC",
    :sigla_3=>"TCA",
    :iso_3166_numerico=>796,
    :continente_id=>nil},
   {:id=>230,
    :nome_ingles=>"Tuvalu",
    :nome=>"Tuvalu",
    :nome_oficial=>"",
    :sigla_2=>"TV",
    :sigla_3=>"TUV",
    :iso_3166_numerico=>798,
    :continente_id=>nil},
   {:id=>231,
    :nome_ingles=>"Uganda",
    :nome=>"Uganda",
    :nome_oficial=>"",
    :sigla_2=>"UG",
    :sigla_3=>"UGA",
    :iso_3166_numerico=>800,
    :continente_id=>1},
   {:id=>232,
    :nome_ingles=>"Ukraine",
    :nome=>"Ucrânia",
    :nome_oficial=>"",
    :sigla_2=>"UA",
    :sigla_3=>"UKR",
    :iso_3166_numerico=>804,
    :continente_id=>7},
   {:id=>233,
    :nome_ingles=>"United Arab Emirates (the)",
    :nome=>"Emirados Árabes Unidos",
    :nome_oficial=>"Emirados Árabes Unidos",
    :sigla_2=>"AE",
    :sigla_3=>"ARE",
    :iso_3166_numerico=>784,
    :continente_id=>6},
   {:id=>234,
    :nome_ingles=>
     "United Kingdom of Great Britain and Northern Ireland (the)",
    :nome=>"Reino Unido",
    :nome_oficial=>"Reino Unido da Grã-Bretanha e Irlanda do Norte",
    :sigla_2=>"GB",
    :sigla_3=>"GBR",
    :iso_3166_numerico=>826,
    :continente_id=>7},
   {:id=>235,
    :nome_ingles=>"United States Minor Outlying Islands (the)",
    :nome=>"Ilhas Menores dos Estados Unidos",
    :nome_oficial=>"",
    :sigla_2=>"UM",
    :sigla_3=>"UMI",
    :iso_3166_numerico=>581,
    :continente_id=>nil},
   {:id=>236,
    :nome_ingles=>"United States of America (the)",
    :nome=>"Estados Unidos da América",
    :nome_oficial=>"",
    :sigla_2=>"US",
    :sigla_3=>"USA",
    :iso_3166_numerico=>840,
    :continente_id=>2},
   {:id=>237,
    :nome_ingles=>"Uruguay",
    :nome=>"Uruguai",
    :nome_oficial=>"",
    :sigla_2=>"UY",
    :sigla_3=>"URY",
    :iso_3166_numerico=>858,
    :continente_id=>4},
   {:id=>238,
    :nome_ingles=>"Uzbekistan",
    :nome=>"Uzbequistão",
    :nome_oficial=>"",
    :sigla_2=>"UZ",
    :sigla_3=>"UZB",
    :iso_3166_numerico=>860,
    :continente_id=>nil},
   {:id=>239,
    :nome_ingles=>"Vanuatu",
    :nome=>"Vanuatu",
    :nome_oficial=>"",
    :sigla_2=>"VU",
    :sigla_3=>"VUT",
    :iso_3166_numerico=>548,
    :continente_id=>nil},
   {:id=>240,
    :nome_ingles=>"Venezuela (Bolivarian Republic of)",
    :nome=>"Venezuela",
    :nome_oficial=>"República Bolivariana da Venezuela",
    :sigla_2=>"VE",
    :sigla_3=>"VEN",
    :iso_3166_numerico=>862,
    :continente_id=>4},
   {:id=>241,
    :nome_ingles=>"Viet Nam",
    :nome=>"Vietnã",
    :nome_oficial=>"",
    :sigla_2=>"VN",
    :sigla_3=>"VNM",
    :iso_3166_numerico=>704,
    :continente_id=>nil},
   {:id=>242,
    :nome_ingles=>"Virgin Islands (British)",
    :nome=>"Ilhas Virgens (Britânica)",
    :nome_oficial=>"",
    :sigla_2=>"VG",
    :sigla_3=>"VGB",
    :iso_3166_numerico=>92,
    :continente_id=>nil},
   {:id=>243,
    :nome_ingles=>"Virgin Islands (U.S.)",
    :nome=>"Ilhas Virgens (EUA)",
    :nome_oficial=>"",
    :sigla_2=>"VI",
    :sigla_3=>"VIR",
    :iso_3166_numerico=>850,
    :continente_id=>nil},
   {:id=>244,
    :nome_ingles=>"Wallis and Futuna",
    :nome=>"Wallis e Futuna",
    :nome_oficial=>"",
    :sigla_2=>"WF",
    :sigla_3=>"WLF",
    :iso_3166_numerico=>876,
    :continente_id=>nil},
   {:id=>245,
    :nome_ingles=>"Western Sahara",
    :nome=>"Saara Ocidental",
    :nome_oficial=>"",
    :sigla_2=>"EH",
    :sigla_3=>"ESH",
    :iso_3166_numerico=>732,
    :continente_id=>nil},
   {:id=>246,
    :nome_ingles=>"Yemen",
    :nome=>"Iêmen",
    :nome_oficial=>"",
    :sigla_2=>"YE",
    :sigla_3=>"YEM",
    :iso_3166_numerico=>887,
    :continente_id=>nil},
   {:id=>247,
    :nome_ingles=>"Zambia",
    :nome=>"Zâmbia",
    :nome_oficial=>"",
    :sigla_2=>"ZM",
    :sigla_3=>"ZMB",
    :iso_3166_numerico=>894,
    :continente_id=>nil},
   {:id=>248,
    :nome_ingles=>"Zimbabwe",
    :nome=>"Zimbábue",
    :nome_oficial=>"",
    :sigla_2=>"ZW",
    :sigla_3=>"ZWE",
    :iso_3166_numerico=>716,
    :continente_id=>nil},
   {:id=>249,
    :nome_ingles=>"Åland Islands",
    :nome=>"Alanda",
    :nome_oficial=>"",
    :sigla_2=>"AX",
    :sigla_3=>"ALA",
    :iso_3166_numerico=>248,
    :continente_id=>nil}
])

# tipos de instrumentos
InstrumentoTipo.destroy_all
InstrumentoTipo.create([
  {:id=>1, :tipo=>"escala"},
  {:id=>2, :tipo=>"teste"},
  {:id=>3, :tipo=>"formulário"},
  {:id=>4, :tipo=>"bateria"}
])

# funções psicológicas
PsicologiaFuncao.destroy_all
PsicologiaFuncao.create([
  {:id=>1, :nome=>"memória", :descricao=>nil},
  {:id=>2, :nome=>"percepção", :descricao=>nil},
  {:id=>3, :nome=>"atenção", :descricao=>nil},
  {:id=>4, :nome=>"compreensão", :descricao=>nil},
  {:id=>5, :nome=>"linguagem", :descricao=>nil},
  {:id=>6, :nome=>"motricidade", :descricao=>nil},
  {:id=>7, :nome=>"funções executivas", :descricao=>nil},
  {:id=>8, :nome=>"inteligência", :descricao=>nil},
  {:id=>9, :nome=>"habilidades sociais", :descricao=>nil},
  {:id=>10, :nome=>"adaptação", :descricao=>nil},
  {:id=>11, :nome=>"planejamento", :descricao=>nil},
  {:id=>12, :nome=>"humor", :descricao=>nil},
  {:id=>13, :nome=>"julgamento", :descricao=>nil}
])

# subfunções psicológicas muahaha
PsicologiaSubfuncao.destroy_all
PsicologiaSubfuncao.create([
  {:id=>1,
   :psicologia_funcao_id=>1,
   :nome=>"episódica",
   :descricao=>
   "memória declarativa de resgate de eventos pesoais com marcação temporal"},
     {:id=>2,
      :psicologia_funcao_id=>1,
      :nome=>"semântica",
      :descricao=>
   "memória declarativa que se relaciona com significados, compreensão e conhecimentos baseados em conceitos"},
     {:id=>3,
      :psicologia_funcao_id=>1,
      :nome=>"espacial",
      :descricao=>"memória declarativa referente ao espaço"},
      {:id=>4,
       :psicologia_funcao_id=>1,
       :nome=>"temporal",
       :descricao=>"memória declarativa referente ao tempo"},
       {:id=>5,
        :psicologia_funcao_id=>1,
        :nome=>"visuoespacial",
        :descricao=>
   "memória declarativa referente à organização espacial baseada em elementos visuais"},
     {:id=>6,
      :psicologia_funcao_id=>1,
      :nome=>"motora",
      :descricao=>
   "memória implícita sobre movimentos a serem realizados em determinado contexto"},
     {:id=>7,
      :psicologia_funcao_id=>1,
      :nome=>"visuomotora",
      :descricao=>
   "memória implícita relacionada à recuperação de movimentos baseados em estímulos visuais"},
     {:id=>8,
      :psicologia_funcao_id=>1,
      :nome=>"operacional",
      :descricao=>
   "memória implícita que é ativada para que operações mentais sejam executadas (atividades semelhantes)"},
   {:id=>9,
    :psicologia_funcao_id=>1,
    :nome=>"prospectiva",
    :descricao=>"memória implícita sobre ação a ser realizada futuramente"},
    {:id=>10,
     :psicologia_funcao_id=>7,
     :nome=>"raciocínio abstrato",
     :descricao=>nil},
     {:id=>11,
      :psicologia_funcao_id=>7,
      :nome=>"conceitualização",
      :descricao=>nil},
      {:id=>12,
       :psicologia_funcao_id=>7,
       :nome=>"flexibilidade mental",
       :descricao=>nil},
       {:id=>13,
        :psicologia_funcao_id=>7,
        :nome=>"programação motora",
        :descricao=>nil},
        {:id=>14,
         :psicologia_funcao_id=>7,
         :nome=>"resistência à interferência",
         :descricao=>nil},
         {:id=>15,
          :psicologia_funcao_id=>7,
          :nome=>"autorregulação",
          :descricao=>nil},
          {:id=>16,
           :psicologia_funcao_id=>7,
           :nome=>"controle inibitório",
           :descricao=>nil},
           {:id=>17,
            :psicologia_funcao_id=>5,
            :nome=>"fonológica",
            :descricao=>nil},
            {:id=>18,
             :psicologia_funcao_id=>5,
             :nome=>"semântica",
             :descricao=>nil},
             {:id=>19,
              :psicologia_funcao_id=>5,
              :nome=>"sintática",
              :descricao=>nil},
              {:id=>20,
               :psicologia_funcao_id=>9,
               :nome=>"compreensão social",
               :descricao=>nil},
               {:id=>21,
                :psicologia_funcao_id=>9,
                :nome=>"geração de opções",
                :descricao=>nil},
                {:id=>22,
                 :psicologia_funcao_id=>9,
                 :nome=>"emissão de escolha",
                 :descricao=>nil},
                 {:id=>23,
                  :psicologia_funcao_id=>9,
                  :nome=>"assertividade",
                  :descricao=>nil},
                  {:id=>24,
                   :psicologia_funcao_id=>9,
                   :nome=>"teoria da mente",
                   :descricao=>nil},
                   {:id=>25, :psicologia_funcao_id=>3, :nome=>"seletiva", :descricao=>nil},
                   {:id=>26,
                    :psicologia_funcao_id=>3,
                    :nome=>"sustentada",
                    :descricao=>nil},
                    {:id=>27,
                     :psicologia_funcao_id=>3,
                     :nome=>"alternada",
                     :descricao=>nil},
                     {:id=>28,
                      :psicologia_funcao_id=>10,
                      :nome=>"flexibilidade cognitiva",
                      :descricao=>nil},
                      {:id=>29,
                       :psicologia_funcao_id=>8,
                       :nome=>"raciocínio",
                       :descricao=>nil},
                       {:id=>30,
                        :psicologia_funcao_id=>8,
                        :nome=>"abstração",
                        :descricao=>nil},
                        {:id=>31,
                         :psicologia_funcao_id=>8,
                         :nome=>"pensamento",
                         :descricao=>nil},
                         {:id=>32, :psicologia_funcao_id=>2, :nome=>"visual", :descricao=>nil},
                         {:id=>33, :psicologia_funcao_id=>2, :nome=>"auditiva", :descricao=>nil},
                         {:id=>34, :psicologia_funcao_id=>2, :nome=>"tátil", :descricao=>nil},
                         {:id=>35, :psicologia_funcao_id=>2, :nome=>"olfativa", :descricao=>nil},
                         {:id=>36,
                          :psicologia_funcao_id=>6,
                          :nome=>"coordenação motora grossa",
                          :descricao=>nil},
                          {:id=>37,
                           :psicologia_funcao_id=>6,
                           :nome=>"coordenação motora fina",
                           :descricao=>nil},
                           {:id=>38,
                            :psicologia_funcao_id=>10,
                            :nome=>"matemática simples",
                            :descricao=>nil},
                            {:id=>39,
                             :psicologia_funcao_id=>10,
                             :nome=>"autonomia",
                             :descricao=>nil},
                             {:id=>40, :psicologia_funcao_id=>4, :nome=>"leitura", :descricao=>nil},
                             {:id=>41, :psicologia_funcao_id=>4, :nome=>"escrita", :descricao=>nil},
                             {:id=>42,
                              :psicologia_funcao_id=>4,
                              :nome=>"matemática",
                              :descricao=>nil},
                              {:id=>43,
                               :psicologia_funcao_id=>6,
                               :nome=>"lateralidade",
                               :descricao=>nil},
                               {:id=>44,
                                :psicologia_funcao_id=>6,
                                :nome=>"adaptativa",
                                :descricao=>nil},
                                {:id=>45,
                                 :psicologia_funcao_id=>9,
                                 :nome=>"controle emocional",
                                 :descricao=>nil},
                                 {:id=>46,
                                  :psicologia_funcao_id=>9,
                                  :nome=>"comunicação não-verbal",
                                  :descricao=>nil},
                                  {:id=>47,
                                   :psicologia_funcao_id=>10,
                                   :nome=>"velocidade de processamento",
                                   :descricao=>nil},
                                   {:id=>48,
                                    :psicologia_funcao_id=>12,
                                    :nome=>"depressão",
                                    :descricao=>nil},
                                    {:id=>49,
                                     :psicologia_funcao_id=>12,
                                     :nome=>"ansiedade",
                                     :descricao=>nil},
                                     {:id=>50, :psicologia_funcao_id=>10, :nome=>"stress", :descricao=>nil}
])

# plataformas de atendimento
AtendimentoPlataforma.destroy_all
AtendimentoPlataforma.create(nome: "Clínica", site: "", descricao: "Atendimentos realizados na clínica", taxa_fixa: 0, taxa_atendimento: 0)

# motivos de finalização de acompanhamento
AcompanhamentoFinalizacaoMotivo.destroy_all
AcompanhamentoFinalizacaoMotivo.create([
  {:id=>0, :motivo=>"ALTA"},
  {:id=>1, :motivo=>"DESISTÊNCIA"},
  {:id=>2, :motivo=>"ENCAMINHAMENTO"},
  {:id=>3, :motivo=>"DOENÇA INCAPACITANTE"},
  {:id=>4, :motivo=>"FALECIMENTO"},
  {:id=>5, :motivo=>"QUESTÕES FINANCEIRAS"}
])

# tipos de profissionais na clínica
ProfissionalFuncao.destroy_all
ProfissionalFuncao.create([
  {
    :id=>1,
    :funcao=>"Psicólogo",
    :orgao_responsavel=>"Conselho Federal de Psicologia",
    :documento_tipo=>"CRP",
    :flexao_feminino=>nil,
    :servico=>"Psicologia",
    :adjetivo_masc=>"psicológico",
    :adjetivo_fem=>"psicológica",
    :realiza_atendimentos=>1
  },
  {
    :id=>2,
    :funcao=>"Fonoaudiólogo",
    :orgao_responsavel=>"Conselho Federal de Fonoaudiologia",
    :documento_tipo=>"CREFONO",
    :flexao_feminino=>nil,
    :servico=>"Fonoaudiologia",
    :adjetivo_masc=>"fonoaudiológico",
    :adjetivo_fem=>"fonoaudiológica",
    :realiza_atendimentos=>1
  },
  {
    :id=>3,
    :funcao=>"Nutricionista",
    :orgao_responsavel=>"Conselho Federal de Nutrição",
    :documento_tipo=>"CRN",
    :flexao_feminino=>nil,
    :servico=>"Nutrição",
    :adjetivo_masc=>"nutricional",
    :adjetivo_fem=>"nutricional",
    :realiza_atendimentos=>1
  },
  {
    :id=>4,
    :funcao=>"Fisioterapeuta",
    :orgao_responsavel=>"Conselho Federal de Fisioterapia e Terapia Ocupacional",
    :documento_tipo=>"CREFITO",
    :flexao_feminino=>nil,
    :servico=>"Fisioterapia",
    :adjetivo_masc=>"fisioterapêutico",
    :adjetivo_fem=>"fisioterapêutica",
    :realiza_atendimentos=>1
  },
  {
    :id=>5,
    :funcao=>"Secretário",
    :orgao_responsavel=>nil,
    :documento_tipo=>nil,
    :flexao_feminino=>nil,
    :servico=>"Secretaria",
    :adjetivo_masc=>nil,
    :adjetivo_fem=>nil,
    :realiza_atendimentos=>nil
  },
  {
    :id=>6,
    :funcao=>"Pedagogo",
    :orgao_responsavel=>"Conselho Federal de Pedagogia",
    :documento_tipo=>nil,
    :flexao_feminino=>nil,
    :servico=>"Pedagogia",
    :adjetivo_masc=>"pedagógico",
    :adjetivo_fem=>"pedagógica",
    :realiza_atendimentos=>1
  },
  {
    :id=>7,
    :funcao=>"Gestor financeiro",
    :orgao_responsavel=>nil,
    :documento_tipo=>nil,
    :flexao_feminino=>"Gestora financeira",
    :servico=>"Gestão financeira",
    :adjetivo_masc=>nil,
    :adjetivo_fem=>nil,
    :realiza_atendimentos=>nil
  },
  {
    :id=>8,
    :funcao=>"Profissional de Educação Física",
    :orgao_responsavel=>"Conselho Federal de Educação Física",
    :documento_tipo=>"CREF",
    :flexao_feminino=>"Profissional de Educação Física",
    :servico=>"Educação Física",
    :adjetivo_masc=>"físico",
    :adjetivo_fem=>"física",
    :realiza_atendimentos=>true,
  },
])

AtendimentoModalidade.destroy_all
AtendimentoModalidade.create([
  {
    :modalidade=>"teleconsulta"
  },
  {
    :modalidade=>"presencial"
  },
  {
    :modalidade=>"visita domiciliar"
  },
])

AtendimentoLocalTipo.destroy_all
AtendimentoLocalTipo.create([
  {
    :tipo=>"Clínica"
  },
  {
    :tipo=>"Escola"
  },
  {
    :tipo=>"Praça"
  },
  {
    :tipo=>"Parque"
  },
  {
    :tipo=>"Casa"
  },
  {
    :tipo=>"Virtual"
  },
  {
    :tipo=>"Hospital"
  },
  {
    :tipo=>"Igreja"
  },
  {
    :tipo=>"Não especificado"
  },
])

# regioes dos conselhos
CrpRegiao.destroy_all
CrpRegiao.create([
  {"uf_id"=>7, "id"=>1},
  {"uf_id"=>17, "id"=>2},
  {"uf_id"=>5, "id"=>3},
  {"uf_id"=>13, "id"=>4},
  {"uf_id"=>19, "id"=>5},
  {"uf_id"=>25, "id"=>6},
  {"uf_id"=>21, "id"=>7},
  {"uf_id"=>16, "id"=>8},
  {"uf_id"=>9, "id"=>9},
  {"uf_id"=>3, "id"=>10},
  {"uf_id"=>14, "id"=>10},
  {"uf_id"=>6, "id"=>11},
  {"uf_id"=>24, "id"=>12},
  {"uf_id"=>15, "id"=>13},
  {"uf_id"=>12, "id"=>14},
  {"uf_id"=>2, "id"=>15},
  {"uf_id"=>8, "id"=>16},
  {"uf_id"=>20, "id"=>17},
  {"uf_id"=>11, "id"=>18},
  {"uf_id"=>26, "id"=>19},
  {"uf_id"=>23, "id"=>20},
  {"uf_id"=>4, "id"=>20},
  {"uf_id"=>18, "id"=>21},
  {"uf_id"=>10, "id"=>22},
  {"uf_id"=>27, "id"=>23},
  {"uf_id"=>22, "id"=>24},
  {"uf_id"=>1, "id"=>24}
])

CrnRegiao.destroy_all
CrnRegiao.create([
  {"uf_id"=>27, "id"=>1},
  {"uf_id"=>7, "id"=>1},
  {"uf_id"=>9, "id"=>1},
  {"uf_id"=>11, "id"=>1},
  {"uf_id"=>21, "id"=>2},
  {"uf_id"=>25, "id"=>3},
  {"uf_id"=>12, "id"=>3},
  {"uf_id"=>8, "id"=>4},
  {"uf_id"=>19, "id"=>4},
  {"uf_id"=>26, "id"=>5},
  {"uf_id"=>5, "id"=>5},
  {"uf_id"=>2, "id"=>6},
  {"uf_id"=>20, "id"=>6},
  {"uf_id"=>17, "id"=>6},
  {"uf_id"=>15, "id"=>6},
  {"uf_id"=>14, "id"=>7},
  {"uf_id"=>22, "id"=>7},
  {"uf_id"=>23, "id"=>7},
  {"uf_id"=>4, "id"=>7},
  {"uf_id"=>3, "id"=>7},
  {"uf_id"=>1, "id"=>7},
  {"uf_id"=>16, "id"=>8},
  {"uf_id"=>13, "id"=>9},
  {"uf_id"=>24, "id"=>10},
  {"uf_id"=>18, "id"=>11},
  {"uf_id"=>10, "id"=>11},
  {"uf_id"=>6, "id"=>11}
])

CrefitoRegiao.destroy_all
CrefitoRegiao.create([
  {"uf_id"=>2, "id"=>1},
  {"uf_id"=>17, "id"=>1},
  {"uf_id"=>15, "id"=>1},
  {"uf_id"=>20, "id"=>1},
  {"uf_id"=>19, "id"=>2},
  {"uf_id"=>25, "id"=>3},
  {"uf_id"=>13, "id"=>4},
  {"uf_id"=>21, "id"=>5},
  {"uf_id"=>6, "id"=>6},
  {"uf_id"=>5, "id"=>7},
  {"uf_id"=>16, "id"=>8},
  {"uf_id"=>11, "id"=>9},
  {"uf_id"=>24, "id"=>10},
  {"uf_id"=>7, "id"=>11},
  {"uf_id"=>9, "id"=>11},
  {"uf_id"=>23, "id"=>12},
  {"uf_id"=>27, "id"=>12},
  {"uf_id"=>14, "id"=>12},
  {"uf_id"=>4, "id"=>12},
  {"uf_id"=>3, "id"=>12},
  {"uf_id"=>12, "id"=>13},
  {"uf_id"=>18, "id"=>14},
  {"uf_id"=>8, "id"=>15},
  {"uf_id"=>10, "id"=>16},
  {"uf_id"=>26, "id"=>17},
  {"uf_id"=>22, "id"=>18},
  {"uf_id"=>1, "id"=>18}
])

CrefonoRegiao.destroy_all
CrefonoRegiao.create([
  {"uf_id"=>19, "id"=>1},
  {"uf_id"=>25, "id"=>2},
  {"uf_id"=>24, "id"=>3},
  {"uf_id"=>16, "id"=>3},
  {"uf_id"=>2, "id"=>4},
  {"uf_id"=>26, "id"=>4},
  {"uf_id"=>5, "id"=>4},
  {"uf_id"=>17, "id"=>4},
  {"uf_id"=>15, "id"=>4},
  {"uf_id"=>27, "id"=>5},
  {"uf_id"=>12, "id"=>5},
  {"uf_id"=>11, "id"=>5},
  {"uf_id"=>9, "id"=>5},
  {"uf_id"=>7, "id"=>5},
  {"uf_id"=>13, "id"=>6},
  {"uf_id"=>8, "id"=>6},
  {"uf_id"=>21, "id"=>7},
  {"uf_id"=>10, "id"=>8},
  {"uf_id"=>18, "id"=>8},
  {"uf_id"=>20, "id"=>8},
  {"uf_id"=>6, "id"=>8},
  {"uf_id"=>14, "id"=>9},
  {"uf_id"=>22, "id"=>9},
  {"uf_id"=>23, "id"=>9},
  {"uf_id"=>4, "id"=>9},
  {"uf_id"=>3, "id"=>9},
  {"uf_id"=>1, "id"=>9}
])
